# **Question 1**

In [1]:
import numpy as np

In [2]:
a = np.arange(2,50,3)

In [3]:
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# **Question 2**

In [7]:
a = 0
l1 = []
l2 = []

In [8]:
for i in range(0,5):
  a = int(input("Enter number {} into the list 1 :".format(i+1)))
  l1.append(a)
print("List 1 is : ",l1)

Enter number 1 into the list 1 :11
Enter number 2 into the list 1 :21
Enter number 3 into the list 1 :31
Enter number 4 into the list 1 :41
Enter number 5 into the list 1 :51
List 1 is :  [11, 21, 31, 41, 51]


In [9]:
for i in range(0,5):
  a = int(input("Enter number {} into the list 2 :".format(i+1)))
  l2.append(a)
print("List 2 is :",l2)

Enter number 1 into the list 2 :61
Enter number 2 into the list 2 :71
Enter number 3 into the list 2 :81
Enter number 4 into the list 2 :91
Enter number 5 into the list 2 :101
List 2 is : [61, 71, 81, 91, 101]


In [11]:
n1 = np.array(l1)
n2 = np.array(l2)

In [20]:
print(n1)
print(n2)

[11 21 31 41 51] int64
[ 61  71  81  91 101] int64


In [23]:
n3 = np.concatenate((n1,n2), axis=0)

In [24]:
n3

array([ 11,  21,  31,  41,  51,  61,  71,  81,  91, 101])

# **Question 3**

In [25]:
n3.dtype

dtype('int64')

In [26]:
n3.size

10

# **Question 4**

In [33]:
e1 = np.array([1,2,3,4,5,6,7,8])

In [34]:
e1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
e1 = np.expand_dims(e1, axis=1)

In [37]:
e1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [38]:
e1.ndim

2

# **Question 5**

In [39]:
h1 = np.array([1,2,3,4,5])

In [40]:
v1 = np.array([6,7,8,9,0])

In [42]:
np.hstack((h1,v1))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [43]:
np.vstack((h1,v1))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

# **Question 6**

In [45]:
un, cn = np.unique(h1,return_counts=True)

In [47]:
print("Unique elements are :",un)
print("Counts of unique elements are :",cn)

Unique elements are : [1 2 3 4 5]
Counts of unique elements are : [1 1 1 1 1]
